# Generated by Django 5.1.2 on 2025-03-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(choices=[('Tênis', 'Tênis'), ('Bicicleta', 'Bicicleta'), ('Dispositivo Inteligente', 'Dispositivo Inteligente')], default='Tênis', help_text='Selecione o equipamento.', max_length=30, verbose_name='Equipamento.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
