# Generated by Django 5.1.2 on 2025-03-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0003_tipoesporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('Homem', 'Homem'), ('Mulher', 'Mulher'), ('Não binário', 'Não binário'), ('Não informado', 'Não informado')], default='Não informado', help_text='Selecione o gênero.', max_length=30, verbose_name='Gênero.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='tipoesporte',
            name='esporte',
            field=models.CharField(choices=[('Corrida', 'Corrida'), ('Corrida de trilhas', 'Corrida de trilhas'), ('Treino de bicicleta', 'Treino de bicicleta'), ('Caminhada', 'Caminhada'), ('Treino de alta intensidade', 'Treino de alta intensidade'), ('Treino de força', 'Treino de força'), ('Treino aeróbico', 'Treino aeróbico'), ('Natação', 'Natação')], default='Corrida', help_text='Selecione o esporte.', max_length=30, verbose_name='Esporte.'),
        ),
    ]
