# Generated by Django 5.0 on 2025-03-24 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0004_tipogenero_alter_tipoesporte_esporte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoequipamento',
            options={'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='tipoesporte',
            options={'verbose_name': 'Esporte', 'verbose_name_plural': 'Esportes'},
        ),
        migrations.AlterModelOptions(
            name='tipogenero',
            options={'verbose_name': 'Gênero', 'verbose_name_plural': 'Gêneros'},
        ),
        migrations.AlterModelOptions(
            name='tipomarca',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
    ]
