# Generated by Django 5.1.2 on 2025-03-24 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descrição para um exemplo.', max_length=100, verbose_name='Descrição')),
                ('quality', models.IntegerField(default=50, help_text='Valor número para a qualidade do exemplo. Entre 0 e 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Qualidade')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo financeiro. Valores entre 0 e 1000.', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Saldo')),
                ('percentage', models.FloatField(blank=True, default=0.0, help_text='Um exemplo de Float. Entre o e 100. Diversas casas decimais.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage')),
                ('email', models.EmailField(help_text='E-mail do exemplo.', max_length=254, unique=True, verbose_name='E-mail')),
                ('url', models.URLField(help_text='URL externa.', max_length=254, verbose_name='URL')),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('CAN', 'Cancelado'), ('WAR', 'Alerta'), ('REA', 'Pronto'), ('FIN', 'Finalizado')], default='NEW', help_text='Selecione o status para o exemplo.', max_length=3, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Exemplo',
                'verbose_name_plural': 'Exemplos',
                'ordering': ('status', '-description'),
            },
        ),
    ]
