# Generated by Django 5.0 on 2025-03-24 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=100, verbose_name='CPF')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('number', models.CharField(max_length=100, verbose_name='Número do passaporte')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('expiration_date', models.DateField(verbose_name='Data de vencimento')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aula.person')),
            ],
        ),
    ]
