# Generated by Django 5.0 on 2025-03-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_reporter_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='magazine',
            field=models.ManyToManyField(to='aula.magazine'),
        ),
    ]
